// <auto-generated />
using System;
using EpitecCMSApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpitecCMSApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220823231733_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EpitecCMSApp.Shared.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2efb90d-270f-4513-b209-5034da2fc5e4"),
                            birthDate = new DateTime(2001, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Wasim",
                            lastName = "Algamal",
                            phoneNum = "3133984347"
                        },
                        new
                        {
                            Id = new Guid("afe8638f-1e8e-4926-a4e4-64ab88b75b65"),
                            birthDate = new DateTime(2002, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "John",
                            lastName = "Smith",
                            phoneNum = "5556667777"
                        },
                        new
                        {
                            Id = new Guid("a7d37b08-962e-4ceb-913f-a54c5fee7207"),
                            birthDate = new DateTime(1988, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Bill",
                            lastName = "Blokovitch",
                            phoneNum = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("e7044ea5-b311-4be4-888f-d113527e6ba1"),
                            birthDate = new DateTime(1997, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Sam",
                            lastName = "Hyde",
                            phoneNum = "11123456789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
